version: "3.1"
services:
    httpd:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./httpd/www:/var/www/html
            - ./httpd/conf/sites-available:/etc/apache2/sites-available
        links:
            - mysql
        networks:
            - default
        restart: always

    mysql:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
        volumes:
            - ./mysql/dump:/docker-entrypoint-initdb.d
            - ./mysql/conf:/etc/mysql/conf.d
            - mysql_vol:/var/lib/mysql
        networks:
            - default
        restart: always

volumes:
    mysql_vol: